dist: xenial

language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2/repository
before_install: unset _JAVA_OPTIONS
install: true
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: never
